plugins { id 'com.android.application' }

android {
    namespace 'com.soroush.agent'
    compileSdk 35

    defaultConfig {
        applicationId 'com.soroush.agent'
        minSdk 26
        targetSdk 35
        versionCode 10
        versionName '2.1.1-alpha4-testreport'
    }

    signingConfigs {
        release {
            storeFile file(System.getenv("KEYSTORE_FILE") ?: "soroush-release.jks")
            storePassword System.getenv("ANDROID_KEYSTORE_PASSWORD")
            keyAlias System.getenv("ANDROID_KEY_ALIAS")
            keyPassword System.getenv("ANDROID_KEY_PASSWORD")
        }
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.release
        }
    }
}
