name: Generate Android Keystore

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "17"

      - name: Generate keystore
        run: |
          keytool -genkeypair \
            -v \
            -keystore soroush-release.jks \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -alias soroush \
            -storepass "@soroush#84@" \
            -keypass "@soroush#84@" \
            -dname "CN=Soroush Agent, OU=Personal, O=Soroush, L=Tehran, ST=Tehran, C=IR"

      - name: Convert keystore to Base64
        run: |
          base64 -w 0 soroush-release.jks > keystore-base64.txt

      - name: Upload keystore files
        uses: actions/upload-artifact@v4
        with:
          name: soroush-keystore
          path: |
            soroush-release.jks
            keystore-base64.txt
